version: "3.9"

services:
  goit-core:
    build: .
    container_name: goit-core
    ports:
      - "50051:50051"
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # mantém dados mesmo se cair

volumes:
  mongo_data:
